// Wrapper para manejar errores async/await automÃ¡ticamente
export const asyncHandler = (fn) => {
  return (req, res, next) => {
    Promise.resolve(fn(req, res, next)).catch(next)
  }
}
